---
- name: Post-provisioning configuration
  hosts: all
  become: yes
  tasks:
    - name: Set timezone to Asia/Shanghai using command
      ansible.builtin.command: timedatectl set-timezone Asia/Shanghai
      changed_when: false

    - name: Configure NTP server
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: "server 10.220.1.254 iburst"
        insertafter: '^#?server'
        state: present
      notify: Restart chrony

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chronyd
        state: restarted
